### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by DerGuteWolf** [jasper07/openui5-googlemaps#1]
When the application page is loaded via https, google stuff needs also be loaded from https, otherwise the browsers won't load it because of mixed content prohibition.

Please change the line in loadScripts to
Loader.defaultUrl = location.protocol.replace('file', 'https')+'//maps.google.com/maps/api/js?';
and the line in markerclusterer to
MarkerClusterer.IMAGE_PATH = location.protocol.replace('file', 'https')+"//google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m";

**Comment by jasper07** [comment]
i believe this was fixed

**Comment by DerGuteWolf** [comment]
Yes, indeed, this is fixed, sorry, forgot to close the issue when I noticed this.
