### ISSUE TITLE
gulp release task quesion?

### ISSUE THREAD

**Issue by js1972** [jasper07/openui5-googlemaps#10]
What is the release task doing?
It looks to be adding any tracked file changes to the current branch; then committing with a release message and adding a tag for that release.

What I'm unsure of is what happens next... You force overwrite the gh-pages branch with master then push it to github.

As the openui5 library has been removed from this repo will your gh-pages stuff still work ok?

I've stopped tracking the build directory in my fork and wondering whether to use the release task...

;-)

**Comment by jasper07** [comment]
hey mate busy with work, just saw the pull requests, approved them, will look into the issues when i get some free time.

wrt to OpenUi5 and the repo, am now using the CDN fro Gh-pages and sampes, tested in a few browsers, so far so good

**Comment by jasper07** [comment]
"What I'm unsure of is what happens next... You force overwrite the gh-pages branch with master then push it to github."

github pages get built from own branch "gh-pages", i push any changes there so they show up
