### ISSUE TITLE
Load Library on WebIDE and Launchpad

### ISSUE THREAD

**Issue by jgtcodilog** [jasper07/openui5-googlemaps#16]
Hi John, 

Have you succeed to do work the add-on with WebIDE and Launchpad ?
As you have mentionned on previous Issues, i tried to : 

var myRootPath = jQuery.sap.getModulePath("CustomerDB");
sap.ui.getCore().loadLibrary("openui5.googlemaps", [myRootPath,"openui5/googlemaps/"].join("/"));

But it doesn't work and produced the following error : 
Uncaught Error: found in negative cache: 'com/codilog/Component.js' from ../../../../../webapp/Component.js: Error: failed to load 'openui5/googlemaps/library.js' from ../../../../../resources/CustomerDB/openui5/googlemaps/library.js: 404 - Not Found

Have you a tips ?

**Comment by jasper07** [comment]
looking on slack i can see that the googlemaps library is under 
CustomerDB/js

in which case you will nee to do something like  

sap.ui.getCore().loadLibrary("openui5.googlemaps", [myRootPath,"js"].join("/"));

**Comment by jgtcodilog** [comment]
Hello John, 
I have tested several method.

I have tried your solution, and no good result :(
My tree : CustomerDB/webapp/openui5/googlemaps/
And Component.js under webapp

In component.js : 
var myRootPath = jQuery.sap.getModulePath("CustomerDB");
sap.ui.getCore().loadLibrary("openui5.googlemaps", [myRootPath,"openui5/googlemaps/"].join("/"));

And the error message : 

Uncaught Error: found in negative cache: 'com/codilog/Component.js' from ../../../../../webapp/Component.js: Error: failed to load 'openui5/googlemaps/library.js' from ../../../../../resources/CustomerDB/openui5/googlemaps/library.js: 404 - Not Found
