### ISSUE TITLE
Setting height to 100%

### ISSUE THREAD

**Issue by gepparta** [jasper07/openui5-googlemaps#18]
Hi jasper07,

I was about to write you an issue.
Actually I have solved it viewing the demo "directionstestwaypoints".

Maybe it is a word worth in your README.file that to achive a 100% responsive map it is needed a special css config for ma1-map. :-)

Kind regards,
Alex

**Comment by jasper07** [comment]
contributions welcome

**Comment by Prateek057** [comment]
Hi @gepparta & @gepparta ,

I have tried adding css for 100% height, but the map disappears if I use the below css code.
```
#__xmlview4--map-map, #__xmlview4--map{
	height: 100% !important;
}
```

can you tell me how to override the element style height of 20em, so that I can fit it in a VBox.

Thanks 
Prateek
