### ISSUE TITLE
Marker cluster images are not available

### ISSUE THREAD

**Issue by alexander-fire** [jasper07/openui5-googlemaps#19]
The marker cluster images are not available in your sample.

![2016-05-25 09_48_29-program manager](https://cloud.githubusercontent.com/assets/18258441/15532058/0adb901c-225e-11e6-8091-5e9a375f1640.png)

**Comment by jasper07** [comment]
hi alexander

can only imagine the number of sites that were affected by this move

https://github.com/googlemaps/js-marker-clusterer/issues/59

I fixed by downloading the images and adding them to a local theme.  

Cheers
JSP
