### ISSUE TITLE
using type in Markers Info Parts

### ISSUE THREAD

**Issue by gepparta** [jasper07/openui5-googlemaps#20]
Hello,

I'm using your maps abstraction and its a lot of fun.
Thank you very much for publishing it.

I would like to know how I can use an odata type like this:

``` javascript
var oMarkers = new openui5.googlemaps.Marker({
    lat : "{latitude}",
    lng : "{longitude}",
    info : {
        parts : [ {
                path : 'name'
        }, {
                path : 'timeFrom',
                type : new sap.ui.model.odata.type.Time()
        }, {
                path : 'timeTo',
                type : new sap.ui.model.odata.type.Time()
        } ]
    },
    click : oController.onMarkerClick
});
```

this example don't work with your markes :-(

PS: I've already found examples like "formatter:'util.Formatter.info'", but I would prefer the standard way if it is possible.

Is it possible in with your maps abstraction?

kind regards,
Alex

**Comment by jasper07** [comment]
You question doesnt really relate to an issue with the library, the question relates to expression binding in xml views, 

please ask on Stackoverflow and see if anyone can help there

JSP
