### ISSUE TITLE
Fitbounds method

### ISSUE THREAD

**Issue by a-feeroz** [jasper07/openui5-googlemaps#24]
Hi jasper07,

I am using this library for an aggregation binding of multiple co-ordinates on the google maps. However, if the co-ordinates are far apart, I am unable to set the zoom of the map accordingly and get all the co-ords in the same window without manual zoom.

I checked the google maps documentation and there is a method called as "fitBounds" which is used to bring all the markers in the same view. Can you please implement that in your library. I extend my contribution in this.

you can reach me on : arshadfeeroz01@gmail.com

Thank you
Arshad Feeroz

**Comment by jasper07** [comment]
Hi Arshad

I added a FitToMarkers feature to the Map control, If set, the zoom level is set such that all markers are brought into view. It uses the Markers position to determine the bounds of the map, if you need to do something similar for other positions, the code should give you a good idea of how it maybe implemented. 

```xml
  <gmaps:Map height="250px" zoom="12" lat="-33.895" lng="151.275" fitToMarkers="true">
        <gmaps:markers>
            <gmaps:Marker lat="-33.895" lng="151.275" info="Bondi Beach" />
            ...
        </gmaps:markers>
    </gmaps:Map>
```
Please contribute back if you make changes you think others may find useful.

Below are links to the code, there are also related updates to demo app and unit tests 

Source [Map._FitToMarkers](https://github.com/jasper07/openui5-googlemaps/blob/master/src/Map.js#L367)
Demo [Mashup](http://jasper07.secondphase.com.au/openui5-googlemaps/samples/app2/)
Unit Test [code](https://github.com/jasper07/openui5-googlemaps/blob/master/test/Marker.js)
Unit Test [runner module](http://jasper07.secondphase.com.au/openui5-googlemaps/test/unitTests.qunit.html?module=Marker%20-%20fit%20to%20markers)
