### ISSUE TITLE
Missingkey

### ISSUE THREAD

**Issue by fredlumm** [jasper07/openui5-googlemaps#25]
Hi, google ask keys for map usage, how can i modify it to add my key?

**Comment by impnguyen** [comment]
I found this 

`                    /**
                     * A Maps API key. To obtain an API key, see developers.google.com/maps/documentation/javascript/tutorial#api_key.
                     */
                    apiKey: {
                        type: "string",
                        defaultValue: ""
                    },`

but insert my apiKey does not work. Any other ideas?

**Comment by impnguyen** [comment]
If you set the apiKey in the preload.json file it will work, because this preloaded file will be loaded in priority. This is not the elegant way, but it works.

**Comment by jasper07** [comment]
there are numerous examples in the samples of using an apikey, have updated the main page to show the easiest method

https://jasper07.secondphase.com.au/openui5-googlemaps/
