### ISSUE TITLE
openui5/googlemaps/library-preload.js: 404 - Not Found

### ISSUE THREAD

**Issue by AdoWebDesig** [jasper07/openui5-googlemaps#26]
I'am getting this error:

jquery.sap.global-dbg.js:993 2017-04-23 12:27:21.861155 failed to load 'openui5/googlemaps/library-preload' (failed to load 'openui5/googlemaps/library-preload.js' from ../../../../../webapp/openui5/googlemaps/library-preload.js: 404 - Not Found) -

Error is correct because there is no library-preload.js but library-preload.json...

**Comment by jasper07** [comment]
> Error is correct because there is no library-preload.js but library-preload.json

UI5 when not in debug mode, will try and load libraries from a preload file, first it will look for a library-preload.js first and if not found will go to openui5/googlemaps/library-preload.json if not found will load the library and then lazy load resources as required.

I am using gulp-ui5-preload to generate the library preload files, it uses the JSON option
