### ISSUE TITLE
Why is the openui5 library included inside the googlemaps library

### ISSUE THREAD

**Issue by js1972** [jasper07/openui5-googlemaps#7]
I notice that the openui5 resources folder is included inside the googlemaps library folder structure. Is there any reason for this duplication or is just that is eases development of the library?

**Comment by jasper07** [comment]
you talking about the Gh-Pages, moving over to CDN is now on the list of things need doing

**Comment by js1972** [comment]
The resources folder is in the maser branch. Should by be necessary as just duplicates the real ui5 library you're using; whether it be the CDN one or ABAP stack etc. 
I just pulled out the googlemaps folder on its own and have it working.
I imagine that while developing the library however it would've been your local copy...  ;-)

**Comment by jasper07** [comment]
moved all samples and gh-pages to CDN
