### ISSUE TITLE
Markers don't move with map

### ISSUE THREAD

**Issue by js1972** [jasper07/openui5-googlemaps#8]
When looking at your search sample - if you drag the map (not the marker) the markers stay in the centre and do not move with the map? However the other samples seem to work fine yet I can't see any difference in the instantiation of the map control...

**Comment by jasper07** [comment]
```
draggable: true ??
```

**Comment by js1972** [comment]
draggable is true. it makes no difference.

Goto this url: http://jasper07.secondphase.com.au/openui5-googlemaps/ and drag the map around without touching the marker and you will see the marker stays glued to the same point which is normal behaviour.

Now goto this url: http://jasper07.secondphase.com.au/openui5-googlemaps/samples/search.html and try dragging the map without touching the marker... The marker has this weird behaviour of staying in the middle of the map an not being fixed.

The drag behaviour of the marker actually works fine - its the drag behaviour of the map which is weird.

**Comment by js1972** [comment]
Actually I think its just that your "search demo" has a closed loop in the {lat}{lng} values.
As you drag the map itself its bound to lat/lng in the model which in-turn moves the marker because the marker position is bound to the same values - thereby causing the strange effect that the marker always stays in the centre of the map...
